backend:
  name: github
  repo: Subaru-Discord/Subaru-Discord.github.io

media_folder: "static/images/uploads"

collections:
  - name: "Articles"
    label: "articles"
    folder: "articles"
    create: true
    fields:
      - { label: "Title", name: "title" }
